--- 
id: soliditybeginner
name: Solidity Beginner Course
summary: Solidity Beginner Course based on the popular https://solidity-by-example.org/ contracts
level: 1
tags: 
  - Solidity
steps:
  - name: 1. Introduction
    path: introduction
  - name: 2. Basic Syntax
    path: basic-syntax
  - name: 3. Primitive Data Types
    path: primitive-data-types
  - name: 4. Variables
    path: variables
  - name: 5.1 Functions - Reading and Writing to a State Variable
    path: functions-reading-and-writing
  - name: 5.2 Functions - View and pure
    path: functions-view-and-pure
  - name: 5.3 Functions - Modifiers and Constructors
    path: functions-modifiers-and-constructors
  - name: 5.4 Functions - Inputs and Outputs
    path: functions-inputs-and-outputs
  - name: 6. Visibility
    path: visibility